### ISSUE TITLE
small error in documentation

### ISSUE THREAD

**Issue by nisavid** [mikeboers/MultiMap#1]
the documentation for MutableMultiMap contains the following:

```
>> m = MutableMultiMap(a=1, b=2)
[...]
>> m.setlist('c', [1, 2, 3])
```

but `setlist` is not an attribute of MutableMultiMap.  i believe it should be `setall`.

**Comment by mikeboers** [comment]
You are correct. I believe in the earliest implementation is was `setlist` but I swapped it for some reason...

Since the intension is to create something that is a drop-in replacement for a number of other multi-value mappings, I think that it should actually support both `setall` and `setlist`, as it already supports `list`, `getlist`, and `getall`.

Seem reasonable?

**Comment by nisavid** [comment]
it's your call, but i'd say you should keep one or the other convention, not both.  Python's standard library quite strictly follows the Zen of Python mantra "There should be one-- and preferably only one --obvious way to do it."

Guido discussed and refuted a similar proposal in a duscussion on c.l.p that can be found [here](http://groups.google.com/group/comp.lang.python/browse_thread/thread/48a26add2d996268/57ab953cb73bc9c7?q=list+pop+group%3Acomp.lang.python+author%3Aguido#), saying "I'm not a big fan of multiple names for the same operation -- sooner or later you're going to read code that uses the other one, so 
you need to learn both, which is more cognitive load."

**Comment by mikeboers** [comment]
I would tend to agree with you/Guido, except for my uses I have been passing this object to at least two different libraries which have different expectations of `getlist` vs `getall`.

My choice would to document the one (eg. `list` and `getlist`), and simply mention that it is will also serve as a substitute for the other classes that the libraries expect.

**Comment by nisavid** [comment]
but `from multimap import MutableMultiMap as M; dir(M)` indicates that `getlist` is not (in the current version) an attribute of `MutableMultiMap`.  if the current version only has `getall` and `setall`, then doesn't this mean that the libraries which use `getlist`/`setlist` are using an old version of `MutableMultiMap`?  if this is the case, then they would have needed a quick search-and-replace anyway upon updating MultiMap to the current version, which would be very easy with `grep -r` and a replace-with-confirmation in a text editor.  it seems like reverting to duplicate names in a subsequent version would be an unnecessary regression.  am i missing something?

**Comment by mikeboers** [comment]
The development version does have a `getlist`; see [the commit](https://github.com/mikeboers/MultiMap/commit/bfeb2cf6c190db14d1d10136249d580a5fd0cec7) which introduced it "recently". I may not have pushed it to PyPi, however...

I'll have to check again, but my uses required the variants on the getting side, but may not need it on the setting side. Perhaps just the documentation change is necessary if `setall` is the way to go (but naming things is hard =P).

**Comment by nisavid** [comment]
of course, do what thou wilt.  it's your library.

but while we're talking about names: i can see why you might remove the "get" from "getlist"--naming getters with "get" is simply redundant and is thankfully almost absent from Python conventions--although i wouldn't make the same decision in this case, simply for the sake of maintaining parallelism with the existing `get`.  however, it seems that "all" is more appropriate than "list" for the following reason.  suppose you go with `getlist`, and you do `m['a'] = [0, 1]`.  then `m.get('a')` will return the list `[0, 1]`, but `m.getlist('a')` will not return that list--it will return a list that contains that list, `[[0,1]]`.  perhaps this isn't too confusing if the MultiMap is used as a final class, but what if a user wraps it in a subclass that provides type-conversion convenience methods such as `getint`, `getfloat`, `getdatetime`, etc., a la [ConfigParser](http://docs.python.org/library/configparser.html?highlight=configparser#ConfigParser.ConfigParser)?  then `getlist` will be quite inconsistent with that interface, but `getall` will still be very clear.

thus i submit my support for `getall` and only `getall`, along with a corresponding `setall`.

**Comment by mikeboers** [comment]
You've won me over; `getall`/`setall` it is (as the primary).

I'll leave `getlist` in there for compatibility reasons with the other library, but will not document it specifically. I don't think there are compatibility issues on the setting side, so that is okay as well. Just need to cleanup the docs as you originally suggested.

=]

**Comment by nisavid** [comment]
awesome, thanks a bunch!

**Comment by mikeboers** [comment]
Done and done.
